# Copyright (C) 2023 Douglas Orend
#
# This is free software, licensed under the BSD 2-Clause License
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for nodogsplash
LUCI_DEPENDS:=+nodogsplash +luci-base
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-nodogsplash

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
