#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@wireguard-ui[-1]
	add ucitrack wireguard-ui
	set ucitrack.@wireguard-ui[-1].init=wireguard-ui
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
